- hosts: all
  sudo: yes
  remote_user: kypros
  roles:
    - williamyeh.prometheus
  vars:
    username: sharedfiles 
    prometheus_components: ["prometheus", "alertmanager", "node_exporter"]
    prometheus_alertmanager_url: "http://localhost:9093/"
  tasks:
    - name: add user
      user: name={{ username }} shell=/bin/bash
    - name: install minimum packages
      apt: update_cache=yes
      apt: upgrade=safe
      apt: name=tmux state=latest
      apt: name=zsh  state=latest
      apt: name=git  state=latest
    - name: td-agent - get gpg key 
      sudo: no
      get_url: url=http://packages.treasuredata.com/GPG-KEY-td-agent dest=GPG-KEY-td-agent
    - name: td-agent - add-key
      shell: apt-key add GPG-KEY-td-agent
    - name: td-agent - add repo
      apt_repository: repo='deb [arch=amd64] http://packages.treasuredata.com/2/ubuntu/trusty/ trusty contrib' state=present
    - name: td-agent - apt-get update 
      apt: update_cache=yes
    - name: td-agent - apt-get install 
      apt: name=td-agent force=yes state=latest
    - name: increment soft limit for fluentd 
      lineinfile: dest=/etc/security/limits.conf 
                  insertbefore='# End of file'
                  line='root            soft    nofile          65536'
                  state=present
    - name: increment hard limit for fluentd 
      lineinfile: dest=/etc/security/limits.conf 
                  insertbefore='# End of file'
                  line='root            hard    nofile          65536'
                  state=present
#    - name: influx db - get deb file
#      get_url: url=https://s3.amazonaws.com/influxdb/influxdb_0.9.4.2_amd64.deb dest=influxdb_0.9.4.2_amd64.deb mode=0644
#    - name: influx db - install deb file 
#      apt: deb=influxdb_0.9.4.2_amd64.deb force=yes state=present
#    - name: influx db - enable and start
#      service: name=influxdb enabled=yes state=started
#    - name: grafana - get deb
#      get_url: url=https://grafanarel.s3.amazonaws.com/builds/grafana_2.1.3_amd64.deb dest=grafana_2.1.3_amd64.deb mode=0644
#    - name: grafana - install
#      apt: deb=grafana_2.1.3_amd64.deb force=yes state=present
#    - name: grafana - enable and start
#      service: name=grafana enabled=yes state=started
#    - name: samba - install samba
#      apt: name=samba state=latest
#    - name: add linux user for samba
#      user: name=smbuser
#    - name: add sambauser
#      shell: echo -e "smbuser\nsmbuser\n" | sudo pdbedit -a -t -u smbuser 
